<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="HomeStaff.aspx.cs" Inherits="PSD_RAAMEN.View.HomeStaff" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <asp:Label ID="Label1" runat="server" Text="Staff bOS"></asp:Label>
            <br />
            <asp:GridView ID="ramenGridView" runat="server" OnRowDeleting="UserGV_RowDeleting" AutoGenerateDeleteButton="true">


            </asp:GridView>
            <br />
            <asp:Button ID="insert_ramen_btn" runat="server" Text="Insert Ramen" OnClick="insert_ramen_btn_Click" />
            <br />
            <asp:TextBox ID="update_ramen_txt" runat="server"></asp:TextBox>
            <asp:Button ID="update_ramen_btn" runat="server" Text="Update Ramen" OnClick="update_ramen_btn_Click" />
        </div>
    </form>
</body>
</html>
